### ISSUE TITLE
Slider 组件手势依赖库升级

### ISSUE THREAD

**Issue by zfkun** [ecomfe/saber-widget#11]
`Slider` & `ImageView` 的手势处理依赖库 `hammer` 做了下强制升级,  see [commit](https://github.com/ecomfe/saber-widget/commit/38d0222913c0d94b5ef61960e0db50b4af545bd7)

> 需依赖的 [dep-hammer](https://github.com/ecomfe/dep-hammer) 更新合并为 `2.0.4+` 版本, [see pr](https://github.com/ecomfe/dep-hammer/pull/1)

> 为避免干扰，新建了个 `feature/hammer2` 的分支

**Comment by treelite** [comment]
感谢坤哥～ 已整理发布新版 [1.4.0](https://github.com/ecomfe/saber-widget/blob/master/History.md#140--2015-06-12)
